DEBUG = True
TITLE = 'Photo albums'
FRONTEND_HOST = '192.168.1.3'
FRONTEND_PORT = 5050
FRONTEND_BASEURL = 'http://showoff'
FRONTEND_PREFIX = 'showoff/'
FRONTEND_FCGI_SOCKET = '/var/lib/showoff/frontend.sock'
ADMIN_HOST = '192.168.1.3'
ADMIN_PORT = 5051
ADMIN_BASEURL = 'http://showoff'
ADMIN_PREFIX = 'showoff_admin/'
ADMIN_FCGI_SOCKET = '/var/lib/showoff/admin.sock'
THUMBNAIL_SIZE = 75
GRID_SIZE = 200
ADMIN_THUMBNAIL_SIZE = 400
THUMBNAILS_PER_PAGE = 12
THUMBNAILS_PER_SMALL_LIST = 8
ADMIN_THUMBNAILS_PER_PAGE = 12
ADMIN_GRID_ITEMS_PER_PAGE = 50
FRONTEND_GRID_ITEMS_PER_PAGE = 50
IMAGE_SIZE = 800
ALLOWED_SIZES = [ 75, 200, 400, 500, 640, 800, 1024, 1600, 'full' ]
THEME = 'default'
CACHE_DIR = '/home/jochem/showoff/data/cache'
EDITS_DIR = '/home/jochem/showoff/data/edits'
SHOWS_DIR = '/home/jochem/showoff/data/shows'
SECRET_KEY = 'CHANGE_THIS'
ALBUMS_DIR = '/home/jochem/Pictures/fotos'
FRONTEND_LIST_TEMPLATES = ['list', 'list_small', 'grid', 'galleria']

